included:
  - Sources

excluded:
  - LocalCodes
  - Sources/PromoKit/Resources

line_length:
  warning: 140
  error: 200
  ignores_urls: true
  ignores_comments: true
  ignores_function_declarations: true
  ignores_interpolated_strings: true

file_length:
  warning: 1500
  error: 3000

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 80
  error: 150

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - x
    - y

opt_in_rules:
  - closure_spacing
  - empty_count
  - empty_string
  - first_where
  - last_where
  - redundant_nil_coalescing
  - sorted_imports
  - toggle_bool
  - prefer_self_type_over_type_of_self

analyzer_rules:
  - unused_import

disabled_rules:
  - trailing_comma
